# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::runtime_optimized 1
    set rt::partid xc7a100tcsg324-2

    source $::env(SYNTH_COMMON)/common_vhdl.tcl

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog}
    {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog}
    {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog}
  } {
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_all_typeA.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_all_typeA_slice.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_allx_typeA.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_allx_typeA_nodelay.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_async_edge_transfer.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_bscan.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_bufr.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut4.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut5.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut6.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut7.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut8.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_generic_memory_read.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_generic_mux.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_match.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_match_nodelay.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_rising_edge_detection.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_startup.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_general_components_lib_v2_0/hdl/verilog/cs_async_transfer.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_register_stat.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_register_p2s.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_register.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_register_ctl.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_register_stream.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/xsdb_interface_buffers.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/labtools_xsdb_slave_lib_v2_1/hdl/verilog/chipscope_xsdb_slave.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_cap_addrgen.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_cap_ctrl_legacy.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_cap_sample_counter.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_cap_window_counter.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_core.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_register.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_reset_ctrl.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_trace_memory.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_trig_match.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_adv_trigger_sequencer.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_counter.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_counter_match.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_fsm_memory_read.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila_trigger.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/ila_v3_0/hdl/verilog/ila_v3_0_ila.v}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_stub.v}
    }
      rt::read_vhdl -lib blk_mem_gen_v8_1 {
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_synth_comp.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_defaults.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_pkg.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_getinit_pkg.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_min_area_pkg.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_bindec.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_mux.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_prim_wrapper.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_prim_wrapper_init.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_prim_width.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_generic_cstr.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_ecc_encoder.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_ecc_decoder.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_input_block.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_output_block.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_axi_read_fsm.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_axi_read_wrapper.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_axi_write_fsm.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_axi_write_wrapper.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_axi_regs_fwd.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_top.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1_synth.vhd}
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/blk_mem_gen_v8_1/blk_mem_gen_v8_1.vhd}
    }
      rt::read_vhdl -lib work {
      {c:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/ila_0/synth/ila_0.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/XADC module/XADC_pkg.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/XADC module/interface_XADC.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/PWM module/PWM_pkg.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/PWM module/PWM.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/XADC module/XADCapb.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/PWM module/PWMapb.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/config.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/ahbrom.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/designs/leon3-digilent-nexys4/leon3mp.vhd}
    }
      rt::read_vhdl -lib grlib {
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/version.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/config_types.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/stdlib.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/stdlib/config.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/amba/amba.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/sparc/sparc.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/modgen/multlib.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/modgen/leaves.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/amba/devices.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/amba/ahbmst.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/amba/apbctrl.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/grlib/amba/ahbctrl.vhd}
    }
      rt::read_vhdl -lib techmap {
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/gencomp/gencomp.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allclkgen.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/inferred/memory_inferred.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/memory_unisim.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grgates.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allmem.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram_2p.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allmul.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/inferred/mul_inferred.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/techmult.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/regfile_3p.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/clkgen_unisim.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/buffer_unisim.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram_dp.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncram64.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grlfpw_net.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/grfpw_net.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/gencomp/netcomp.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/tap_unisim.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/techbuf.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkmux.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkand.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/alltap.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/unisim/pads_unisim.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/tap.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncreg.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/syncrambw.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/allpads.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/outpad.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/iopad.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/inpad.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/techmap/maps/clkgen.vhd}
    }
      rt::read_vhdl -lib gaisler {
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmuconfig.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmuiface.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3/leon3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmulrue.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/libmmu.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libfpu.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/arith.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutlbcam.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmulru.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libiu.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutw.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmutlb.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libcache.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/srmmu/mmu.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_icache.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_dcache.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_acache.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/libleon3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/uart.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/net/net.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/misc.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/regfile_3p_l3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/mmu_cache.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/iu3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/mul32.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/arith/div32.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/libdcom.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/memctrl/memctrl.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/tbufmem.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/proc3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grlfpwx.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grfpwxsh.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/grfpwx.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/cachemem.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/libjtagcom.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/ethernet_mac.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/dcom_uart.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/dcom.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/memctrl/sdmctrl.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/leon3x.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/dsu3x.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtagcom2.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtagcom.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/jtag.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/greth_gbit.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/greth.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/apbuart.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/uart/ahbuart.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/spi/spi.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/rstgen.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/gptimer.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/misc/ahbram.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/leon3s.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/leon3v3/dsu3.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/jtag/ahbjtag.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/irqmp/irqmp.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/gaisler/greth/grethm.vhd}
    }
      rt::read_vhdl -lib eth {
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_pkg.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_rstgen.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_tx.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/greth_rx.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_edcl_ahb_mst.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/eth_ahb_mst.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/core/grethc.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/eth/comp/ethcomp.vhd}
    }
      rt::read_vhdl -lib esa {
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/esa/memoryctrl/memoryctrl.vhd}
      {C:/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/imports/grlib-gpl-1.3.4-b4140/lib/esa/memoryctrl/mctrl.vhd}
    }
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-8568-Zotty-LT02/realtime/leon3mp_synth.xdc
    set rt::top leon3mp
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-8568-Zotty-LT02/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
