# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-2
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip {{z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xci}}
set_property used_in_implementation false [get_files {{z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.dcp}}]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files {{z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xci}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.data/wt} [current_project]
set_property parent.project_dir {Z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie} [current_project]
synth_design -top dac_clk -part xc7a100tcsg324-2 -mode out_of_context

rename_ref -prefix_all dac_clk
write_checkpoint -noxdef dac_clk.dcp
report_utilization -file dac_clk_utilization_synth.rpt -pb dac_clk_utilization_synth.pb
if { [catch {
  file copy -force {Z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.runs/dac_clk_synth_1/dac_clk.dcp} {z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.dcp}
  write_verilog -force -mode synth_stub {z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_stub.v}
  write_verilog -force -mode funcsim {z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_funcsim.v}
  write_vhdl -force -mode funcsim {z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_funcsim.vhdl}
} _RESULT ] } { 
  puts "Critical Warning: Unable to successfully create or copy supporting IP files."
}
