# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xci
# IP: The module: 'dac_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xci
# IP: The module: 'dac_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/DAT096/git/ES-Project-Spring-2014/Source code/HW/soundlie/soundlie.srcs/sources_1/ip/dac_clk/dac_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
